# add an API key and update config as needed in `typesense-server.ini`
services:
  typesense:
    image: typesense/typesense:27.1
    restart: unless-stopped
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
      - type: bind
        source: ./typesense-server.ini
        target: /config/typesense-server.ini
    command: '--config=/config/typesense-server.ini'
